name: one_shot
description: The simplest way to build LLM powered applications
version: 1.0.0
repository: https://github.com/lukepighetti/one_shot

environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
