name: one_shot
description: Build simple LLM applications fast. Works with any LLM provider that uses the Open AI chat completions protocol.
version: 1.0.3
repository: https://github.com/lukepighetti/one_shot

environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
